include: package:flutter_lints/flutter.yaml


linter:
  rules:
    prefer_const_constructors: false # Uncomment to disable the `avoid_print` rule
    prefer_const_literals_to_create_immutables: false # Uncomment to enable the `prefer_single_quotes` rule